[package]
name = "assembly_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = [ "derive" ] }
ron = "*"

[dev-dependencies]
divan = "*"

[[bench]]
name = "bench"
harness = false
