[workspace]
resolver = "2"
members = [ "assembly_machine", "nonsembly", ]
default-members = [ "assembly_machine", ]

[profile.release]
lto = true
strip = true

[profile.profiling]
inherits = "release"
debug = true
strip = false
